#!/usr/bin/env python3
"""Bake a build brand into ``src/_build_brand.py`` before packaging.

A frozen app is launched by double-click, so a brand chosen at build time
cannot live in the environment — it has to be inside the bundle. Build scripts
call this before PyInstaller runs and reset it afterwards.

Usage:
    python scripts/set_build_brand.py                       # Updater CE (default)
    python scripts/set_build_brand.py mediatek_installer     # MediaTek Installer
    python scripts/set_build_brand.py --reset                # remove the file
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

BRANDS = ("updater_ce", "mediatek_installer")
TARGET = Path(__file__).resolve().parent.parent / "src" / "_build_brand.py"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description="Set the brand for a frozen build")
    parser.add_argument("brand", nargs="?", default="updater_ce")
    parser.add_argument("--reset", action="store_true", help="remove the generated file")
    args = parser.parse_args(argv)

    if args.reset:
        TARGET.unlink(missing_ok=True)
        print(f"build brand reset ({TARGET.name} removed)")
        return 0

    brand = args.brand.strip().lower().replace("-", "_")
    if brand not in BRANDS:
        print(f"unknown brand {brand!r}; expected one of: {', '.join(BRANDS)}", file=sys.stderr)
        return 2

    TARGET.write_text(
        '"""Generated by scripts/set_build_brand.py at build time — do not commit."""\n'
        f'BUILD_BRAND = "{brand}"\n',
        encoding="utf-8",
    )
    print(f"build brand: {brand} -> {TARGET}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
