"""Diagnostics, persistent logging, and log file export for Updater CE.

Captures, persists, categorizes, and displays diagnostic logs from:
1. Updater CE GUI (application events, downloads, extraction, scatter parsing)
2. SP Flash Tool console mode (stdout, stderr, QT_FLASH_TOOL.log)
3. MTKClient (terminal output, DA communications, USB handshakes)
4. Full unified diagnostic stream
"""

from __future__ import annotations

from collections import deque
from contextlib import contextmanager
from dataclasses import dataclass, field
from datetime import datetime
import io
import logging
import os
from pathlib import Path
import re
import subprocess
import sys
import threading
import time
from typing import Callable, Iterator, Optional, Tuple

from .downloads import downloads_dir
from .paths import IS_MAC, IS_WINDOWS

logger = logging.getLogger(__name__)

# Category constants
CAT_ALL = "all"
CAT_SP = "sp"
CAT_MTK = "mtk"
CAT_GUI = "gui"

_LOCK = threading.RLock()
_LOCAL = threading.local()

# Identical raw messages seen again inside this window are the same physical
# event echoed twice (e.g. a tool line that reaches Diagnostics both through
# its own output stream and through the backend callback), not two events.
DEDUPE_WINDOW_SECONDS = 2.0
_MAX_RECENT_RAW = 256

# Python logging writes every record to the console stream the flash capture
# tees, so a record already stored by the logging handler would be stored a
# second time from its console echo (with a different timestamp/colour prefix,
# which the by-text dedupe above cannot catch). Recent payloads are remembered
# here so the tee can recognise and skip them.
_RECENT_LOGGED: "deque[Tuple[str, float]]" = deque(maxlen=32)
_WS_RE = re.compile(r"\s+")


def _note_logged_text(text: str) -> None:
    """Remember a message just stored by the logging handler."""
    text = _WS_RE.sub(" ", str(text or "").strip())
    # Short generic messages ("done", "ok") are too weak an identity: matching
    # them against a tool line could discard an unrelated event.
    if len(text) >= 12:
        _RECENT_LOGGED.append((text, time.monotonic()))


def _is_console_echo(line: str) -> bool:
    """True when ``line`` is the console echo of an already-stored record."""
    if not _RECENT_LOGGED:
        return False
    text = _WS_RE.sub(" ", str(line or "").strip())
    if not text:
        return False
    now = time.monotonic()
    return any(now - ts < DEDUPE_WINDOW_SECONDS and msg in text for msg, ts in _RECENT_LOGGED)


def logs_dir() -> Path:
    """Directory where persistent diagnostic logs are stored."""
    d = downloads_dir().parent / "logs"
    try:
        d.mkdir(parents=True, exist_ok=True)
    except Exception as e:
        logger.debug("Could not create logs dir %s: %s", d, e)
    return d


def get_log_file(category: str = CAT_ALL) -> Path:
    """Return the absolute Path for a given log category file."""
    ldir = logs_dir()
    if category == CAT_SP:
        return ldir / "sp_flash_tool.log"
    if category == CAT_MTK:
        return ldir / "mtkclient.log"
    if category == CAT_GUI:
        return ldir / "updater_gui.log"
    return ldir / "updater.log"


def available_categories(
    is_mac: Optional[bool] = None,
    is_windows: Optional[bool] = None,
    hidden_mtk: Optional[bool] = None,
) -> list[tuple[str, str]]:
    """Log views worth offering on this host, as (category, label key) pairs.

    SP Flash Tool does not run on macOS, so its output would always be empty
    there; Windows users drive the player with SP Flash Tool unless they have
    revealed the hidden MTKClient options with the M key. Showing a backend a
    platform cannot produce only hides the entries that matter.
    """
    if is_mac is None:
        is_mac = IS_MAC
    if is_windows is None:
        is_windows = IS_WINDOWS
    if hidden_mtk is None:
        try:
            from .device_tracking import hidden_mtk_options_enabled

            hidden_mtk = hidden_mtk_options_enabled()
        except Exception:
            hidden_mtk = False

    cats: list[tuple[str, str]] = [(CAT_ALL, "log_filter_all")]
    if not is_mac:
        cats.append((CAT_SP, "log_filter_sp"))
    if not is_windows or hidden_mtk:
        cats.append((CAT_MTK, "log_filter_mtk"))
    cats.append((CAT_GUI, "log_filter_gui"))
    return cats


def find_sp_qt_flash_tool_log() -> Optional[Path]:
    """Search for the newest internal QT_FLASH_TOOL.log generated by SP Flash Tool."""
    candidates = []
    # 1. Linux staging directory
    try:
        from .linux_sp_flash import stage_dir
        sdir = stage_dir() / "SP_FT_Logs"
        if sdir.is_dir():
            candidates.append(sdir)
    except Exception:
        pass

    # 2. Windows ProgramData directory
    prog_data = Path(os.environ.get("PROGRAMDATA", r"C:\ProgramData")) / "SP_FT_Logs"
    if prog_data.is_dir():
        candidates.append(prog_data)

    # 3. Cache directory fallback
    cache_sp = Path.home() / ".cache" / "innioasis-updater" / "linux_flash_tool" / "SP_FT_Logs"
    if cache_sp.is_dir() and cache_sp not in candidates:
        candidates.append(cache_sp)

    newest_log = None
    newest_mtime = 0.0
    for root in candidates:
        try:
            for sub in root.iterdir():
                if sub.is_dir():
                    log_file = sub / "QT_FLASH_TOOL.log"
                    if log_file.is_file():
                        mtime = log_file.stat().st_mtime
                        if mtime > newest_mtime:
                            newest_mtime = mtime
                            newest_log = log_file
        except Exception:
            continue
    return newest_log


class _ToolStreamTee(io.TextIOBase):
    """Write-through stream wrapper that mirrors complete lines into a sink.

    MTKClient runs in process: its phase messages arrive through the
    ``config.gui`` hook, but everything it (or the USB layer under it) prints
    directly — handshake retries, DA traces, SLA results — plus everything it
    emits through Python logging goes to stdout and disappears with the
    console. Wrapping the stream keeps a copy for Diagnostics, so a finished
    install can still be read back.

    The wrapped stream is never closed and every write is forwarded to it, so
    a console (and the test runner's capture) still sees the output.
    """

    def __init__(self, original, sink: Callable[[str], None], tag: str = ""):
        super().__init__()
        self._original = original
        self._sink = sink
        self._tag = tag
        self._buf = ""

    # ``encoding``/``errors``/``buffer`` are read-only on TextIOBase, so they
    # are exposed as properties of the wrapped stream instead of attributes.
    @property
    def encoding(self):
        return getattr(self._original, "encoding", "utf-8") or "utf-8"

    @property
    def errors(self):
        return getattr(self._original, "errors", "replace") or "replace"

    @property
    def buffer(self):
        return getattr(self._original, "buffer", None)

    def __getattr__(self, name):
        """Delegate anything else (reconfigure, mode, ...) to the real stream."""
        if name.startswith("_"):
            raise AttributeError(name)
        original = self.__dict__.get("_original")
        if original is None:
            raise AttributeError(name)
        return getattr(original, name)

    # -- writing ------------------------------------------------------------
    def write(self, text) -> int:  # type: ignore[override]
        if self._original is not None:
            try:
                self._original.write(text)
            except Exception:
                pass
        self._absorb(str(text))
        return len(text)

    def _absorb(self, text: str) -> None:
        self._buf += text
        while "\n" in self._buf:
            line, self._buf = self._buf.split("\n", 1)
            self._emit(line)
        # A write with no newline (a progress bar, a very long trace) must not
        # grow the buffer without bound.
        if len(self._buf) > 8000:
            self._emit(self._buf)
            self._buf = ""

    def _emit(self, line: str) -> None:
        line = line.rstrip("\r")
        if not line.strip():
            return
        # The logging tree already wrote this record to Diagnostics; do not
        # store its console echo as well.
        if _is_console_echo(line):
            return
        try:
            # The tag may be a callable: the backend (and therefore the right
            # prefix) is only known once dispatch has happened.
            tag = self._tag() if callable(self._tag) else self._tag
            if tag:
                line = f"[{tag}] {line}"
            self._sink(line)
        except Exception:
            pass

    def flush(self) -> None:
        if self._original is not None:
            try:
                self._original.flush()
            except Exception:
                pass
        if self._buf.strip():
            self._emit(self._buf)
        self._buf = ""

    # -- stream protocol ----------------------------------------------------
    def isatty(self) -> bool:
        try:
            return bool(self._original is not None and self._original.isatty())
        except Exception:
            return False

    def fileno(self) -> int:
        if self._original is None:
            raise OSError("underlying stream has no file descriptor")
        return self._original.fileno()

    def detach(self):
        """Hand the real stream over, as a plain stream replacement would.

        mtkclient re-wraps ``sys.stdout`` at import time; letting it detach the
        real stream keeps that import working even if capture were installed
        before it.
        """
        if self._original is None or not hasattr(self._original, "detach"):
            raise io.UnsupportedOperation("detach")
        return self._original.detach()

    def writable(self) -> bool:
        return True

    def readable(self) -> bool:
        return False

    def close(self) -> None:
        # Never close the real console stream: the app keeps printing to it.
        try:
            self.flush()
        except Exception:
            pass


class _DiagnosticsLogHandler(logging.Handler):
    """Mirrors Python logging records into Diagnostics.

    mtkclient logs its library traces (``[LIB]`` lines) and the app logs
    backend failures through the standard logging tree; those records reach a
    console StreamHandler or nothing at all, so they are invisible in a GUI
    build. Re-emitting them here is what makes a ``[LIB]`` trace part of the
    log a user can send to the developer.
    """

    def __init__(self, level: int = logging.INFO):
        super().__init__(level=level)
        self.setFormatter(logging.Formatter("%(name)s - %(message)s"))

    def emit(self, record: logging.LogRecord) -> None:  # noqa: D102
        # Diagnostics logging its own failures must not re-enter this handler.
        if getattr(_LOCAL, "in_log_handler", False):
            return
        _LOCAL.in_log_handler = True
        try:
            message = self.format(record)
            DiagnosticsManager.instance().record_log(message, dedupe=True)
            _note_logged_text(record.getMessage())
        except Exception:
            pass
        finally:
            _LOCAL.in_log_handler = False


class _ToolOutputCapture:
    """Reference-counted stream tee used while a flash is running."""

    def __init__(self):
        self._saved: dict[str, object] = {}
        self._depth = 0
        self._sink: Callable[[str], None] = lambda _line: None
        self._tag = ""

    def install(self, sink: Callable[[str], None], tag: str = "") -> None:
        install_log_capture(include_root=True)
        with _LOCK:
            self._depth += 1
            if self._depth > 1:
                return
            self._sink = sink
            self._tag = tag
            for name in ("stdout", "stderr"):
                original = getattr(sys, name, None)
                if isinstance(original, _ToolStreamTee):
                    continue
                try:
                    setattr(sys, name, _ToolStreamTee(original, self._sink, self._tag))
                    self._saved[name] = original
                except Exception as e:
                    # Losing capture means losing the install's raw tool output,
                    # which is the whole point: say so instead of failing mute.
                    logger.warning("Could not tee sys.%s: %s", name, e)

    def remove(self) -> None:
        with _LOCK:
            self._depth = max(0, self._depth - 1)
            if not self._depth:
                for name, original in self._saved.items():
                    try:
                        setattr(sys, name, original)
                    except Exception:
                        pass
                self._saved.clear()
        remove_log_capture()


_CAPTURE = _ToolOutputCapture()

# Loggers whose records are mirrored app-wide. The root logger is added only
# while a flash runs, so steady-state diagnostics stay free of third-party
# library chatter while an install still captures everything.
_LOG_HANDLER_TARGETS = ("src", "mtkclient")

_LOG_HANDLER_DEPTH = 0
_LOG_HANDLERS: "list[tuple[logging.Logger, logging.Handler]]" = []


def install_log_capture(include_root: bool = False) -> None:
    """Attach the Diagnostics logging handler (idempotent, reference counted).

    Called once for the GUI session and again around each flash, because
    mtkclient reconfigures the logging tree when it is imported and that drops
    handlers attached to the root logger.
    """
    global _LOG_HANDLER_DEPTH
    with _LOCK:
        _LOG_HANDLER_DEPTH += 1
        names = _LOG_HANDLER_TARGETS + (("",) if include_root else ())
        for name in names:
            try:
                target = logging.getLogger(name)
            except Exception:
                continue
            if any(isinstance(h, _DiagnosticsLogHandler) for h in target.handlers):
                continue
            try:
                handler = _DiagnosticsLogHandler()
                target.addHandler(handler)
                _LOG_HANDLERS.append((target, handler))
            except Exception:
                continue


def remove_log_capture() -> None:
    """Release one logging-capture reference; detaches at zero."""
    global _LOG_HANDLER_DEPTH
    with _LOCK:
        _LOG_HANDLER_DEPTH = max(0, _LOG_HANDLER_DEPTH - 1)
        if _LOG_HANDLER_DEPTH:
            return
        for target, handler in _LOG_HANDLERS:
            try:
                target.removeHandler(handler)
                handler.close()
            except Exception:
                pass
        _LOG_HANDLERS.clear()


@contextmanager
def capture_tool_output(sink: Callable[[str], None], tag: str = "") -> Iterator[None]:
    """Tee ``sys.stdout``/``sys.stderr`` (and logging) into ``sink``.

    Used around a flash so output the tooling prints itself is recorded in
    Diagnostics alongside the lines the Updater CE GUI inserts. Nested uses
    share one installation.
    """
    _CAPTURE.install(sink, tag)
    try:
        yield
    finally:
        _CAPTURE.remove()


def reveal_in_file_manager(target_path: Path | str) -> bool:
    """Open the host OS file manager and highlight or display target_path."""
    p = Path(target_path).resolve()
    if not p.exists():
        # Fall back to parent directory if file does not exist yet
        p = p.parent
        if not p.exists():
            p.mkdir(parents=True, exist_ok=True)

    try:
        if sys.platform == "darwin":
            if p.is_file():
                subprocess.run(["open", "-R", str(p)], check=False)
            else:
                subprocess.run(["open", str(p)], check=False)
            return True
        elif os.name == "nt":
            if p.is_file():
                subprocess.run(["explorer", f"/select,{os.path.normpath(str(p))}"], check=False)
            else:
                subprocess.run(["explorer", os.path.normpath(str(p))], check=False)
            return True
        else:
            # Linux: try xdg-open on parent directory or file
            parent_dir = str(p if p.is_dir() else p.parent)
            subprocess.run(["xdg-open", parent_dir], check=False)
            return True
    except Exception as e:
        logger.warning("Could not reveal %s in file manager: %s", target_path, e)
        return False


# ---------------------------------------------------------------------------
# Timestamped log reading: date/time filtering and install sessions
# ---------------------------------------------------------------------------

# Every recorded line is written as "[YYYY-MM-DD HH:MM:SS] message".
LINE_TIMESTAMP_RE = re.compile(r"^\[(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})\]")
_TIMESTAMP_FORMAT = "%Y-%m-%d %H:%M:%S"

# Text that indicates something went wrong. Deliberately broad — a missed
# failure line is worse than a false positive in a filter the user can see and
# undo — but anchored on the words the tooling actually prints.
PROBLEM_RE = re.compile(
    r"(?:\berror\b|\berr\b|fail(?:ed|ure|s)?\b|exception|traceback|\btimeout\b|timed out|"
    r"refused|denied|not found|no such|\bmissing\b|invalid|corrupt|unable to|\bcannot\b|can't|"
    r"unsupported|unrecognized|abort(?:ed)?|\bpanic\b|stall(?:ed)?|warn(?:ing)?\b|"
    r"S_[A-Z0-9_]*ERROR|STATUS_[A-Z0-9_]+)",
    re.IGNORECASE,
)


def parse_line_timestamp(line: str) -> Optional[datetime]:
    """Return the timestamp a recorded line was written with, or None."""
    match = LINE_TIMESTAMP_RE.match(str(line or "").lstrip())
    if not match:
        return None
    try:
        return datetime.strptime(match.group(1), _TIMESTAMP_FORMAT)
    except ValueError:
        return None


def line_is_problem(line: str) -> bool:
    """True when a line looks like a failure worth diagnosing."""
    return bool(PROBLEM_RE.search(str(line or "")))


def _in_window(ts: datetime, start: Optional[datetime], end: Optional[datetime]) -> bool:
    if start is not None and ts < start:
        return False
    if end is not None and ts > end:
        return False
    return True


def filter_log_lines(
    lines,
    start: Optional[datetime] = None,
    end: Optional[datetime] = None,
    problems_only: bool = False,
) -> list[str]:
    """Select the lines inside a date/time window, optionally problems only.

    A line without its own timestamp (a stack trace, a wrapped tool output, the
    QT_FLASH_TOOL.log block) belongs to the timestamped line above it, so it is
    kept exactly when that line is kept. Filtering it away would hide the very
    traceback that explains the failure being investigated.
    """
    out: list[str] = []
    keep_continuations = False
    for raw in lines:
        line = str(raw)
        ts = parse_line_timestamp(line)
        if ts is None:
            if keep_continuations:
                out.append(line)
            continue
        keep = _in_window(ts, start, end)
        if keep and problems_only:
            keep = line_is_problem(line)
        keep_continuations = keep
        if keep:
            out.append(line)
    return out


def log_time_range(lines) -> tuple[Optional[datetime], Optional[datetime]]:
    """(oldest, newest) timestamped moment in ``lines``."""
    stamps = [ts for ts in (parse_line_timestamp(ln) for ln in lines) if ts is not None]
    if not stamps:
        return None, None
    return min(stamps), max(stamps)


@dataclass
class InstallSession:
    """One install attempt, delimited by the session banners in the log."""

    number: int = 0
    started: Optional[datetime] = None
    ended: Optional[datetime] = None
    package: str = ""
    model: str = ""
    method: str = ""
    success: Optional[bool] = None  # None: still running / never completed
    detail: str = ""
    first_line: int = 0
    last_line: int = 0
    problem_lines: int = field(default=0)

    @property
    def running(self) -> bool:
        return self.success is None

    @property
    def status(self) -> str:
        if self.success is None:
            return "running"
        return "ok" if self.success else "failed"


def _parse_session_end(text: str) -> tuple[bool, str]:
    """Split "SUCCESS" / "FAILED (<cause>) at <ts>" into (success, cause)."""
    body = (text or "").strip()
    if body.upper().startswith("SUCCESS"):
        return True, ""
    match = re.search(r"FAILED\s*\((.*)\)\s*(?:at .*)?$", body)
    return False, (match.group(1).strip() if match else body)


def collect_install_sessions(lines) -> list[InstallSession]:
    """Find the install attempts recorded in ``lines``, newest last.

    Sessions are read from the banners ``start_flash_session`` /
    ``end_flash_session`` write, so the user can jump straight to the install
    that failed instead of hunting for it by hand.
    """
    sessions: list[InstallSession] = []
    current: Optional[InstallSession] = None
    for idx, raw in enumerate(lines):
        line = str(raw)
        ts = parse_line_timestamp(line)
        if "INSTALL SESSION STARTED" in line:
            current = InstallSession(
                number=len(sessions) + 1,
                started=ts,
                first_line=idx,
                last_line=idx,
            )
            sessions.append(current)
            continue
        if current is None:
            continue
        current.last_line = idx
        for marker, attr in (
            ("=== Software Package:", "package"),
            ("=== Device Model:", "model"),
            ("=== Flashing Method:", "method"),
        ):
            if marker in line:
                setattr(current, attr, line.split(marker, 1)[1].strip())
                break
        else:
            if "INSTALL SESSION COMPLETED" in line:
                current.success, current.detail = _parse_session_end(
                    line.split("INSTALL SESSION COMPLETED:", 1)[-1]
                )
                current.ended = ts
                current = None
    for session in sessions:
        session.problem_lines = sum(
            1 for ln in lines[session.first_line : session.last_line + 1] if line_is_problem(ln)
        )
    return _merge_repeated_sessions(sessions)


def _merge_repeated_sessions(sessions: list[InstallSession]) -> list[InstallSession]:
    """Collapse banners written twice for the same attempt in the same second."""
    merged: list[InstallSession] = []
    for session in sessions:
        if merged:
            previous = merged[-1]
            same_start = previous.started == session.started
            same_target = (previous.package, previous.model, previous.method) == (
                session.package,
                session.model,
                session.method,
            )
            if same_start and same_target and previous.running:
                previous.last_line = session.last_line
                continue
        session.number = len(merged) + 1
        merged.append(session)
    return merged


def _qt_log_section_lines() -> list[str]:
    """Lines of SP Flash Tool's internal QT_FLASH_TOOL.log, or [] when absent."""
    qt_log = find_sp_qt_flash_tool_log()
    if not qt_log or not qt_log.is_file() or not qt_log.stat().st_size:
        return []
    try:
        content = qt_log.read_text(encoding="utf-8", errors="ignore")
    except Exception:
        return []
    if not content.strip():
        return []
    sep = "-" * 70
    return ["", sep, f"[SP Internal QT_FLASH_TOOL.log from {qt_log}]", sep, *content.splitlines()]


class DiagnosticsManager:
    """Coordinates in-memory log buffering, real-time file persistence, and categorization."""

    _instance: Optional[DiagnosticsManager] = None

    @classmethod
    def instance(cls) -> DiagnosticsManager:
        if cls._instance is None:
            cls._instance = DiagnosticsManager()
        return cls._instance

    def __init__(self, max_buffer_lines: int = 5000):
        self._max_buffer = max_buffer_lines
        self._buffers: dict[str, list[str]] = {
            CAT_ALL: [],
            CAT_SP: [],
            CAT_MTK: [],
            CAT_GUI: [],
        }
        self._active_backend = ""
        self._recent_raw: dict[str, float] = {}
        self._load_disk_history()

    def set_active_backend(self, backend: str):
        """Inform diagnostics about active backend ('sp' or 'mtk') for line classification."""
        with _LOCK:
            self._active_backend = (backend or "").lower()

    def _load_disk_history(self):
        """Pre-populate in-memory buffers with recent lines from on-disk log files."""
        for cat in (CAT_ALL, CAT_SP, CAT_MTK, CAT_GUI):
            fpath = get_log_file(cat)
            if fpath.is_file() and fpath.stat().st_size > 0:
                try:
                    # Keep the tail only, and stream it: a chatty install can
                    # make these files large enough that readlines() is wasteful.
                    with open(fpath, "r", encoding="utf-8", errors="replace") as f:
                        lines = [
                            ln.rstrip("\r\n") for ln in deque(f, maxlen=500)
                        ]
                    self._buffers[cat] = lines
                except Exception:
                    pass

    def clear(self, clear_disk: bool = False):
        """Clear in-memory log buffers, and optionally clear files on disk."""
        with _LOCK:
            for cat in (CAT_ALL, CAT_SP, CAT_MTK, CAT_GUI):
                self._buffers[cat] = []
                if clear_disk:
                    fpath = get_log_file(cat)
                    try:
                        if fpath.is_file():
                            fpath.write_text("", encoding="utf-8")
                    except Exception:
                        pass

    def classify_line(self, line: str) -> str:
        """Determine whether a line belongs to SP Flash Tool, MTKClient, or GUI."""
        clean = str(line or "").strip()
        low = clean.lower()

        # Explicit tool tags
        if clean.startswith(("[SP]", "[QT]")) or "sp_flash" in low or "flash_tool" in low:
            return CAT_SP
        if (
            clean.startswith("[MTK]")
            or "mtkclient" in low
            or "waiting for mtk" in low
            or "mtk device" in low
            or "brom mode" in low
            or "da_handler" in low
            or "daloader" in low
        ):
            return CAT_MTK

        # Contextual classification based on active backend during flash
        if self._active_backend == "sp":
            if any(k in low for k in ("search usb", "brom connected", "of da has been sent",
                                      "download ok", "download failed", "s_ft_", "s_chip", "of image data")):
                return CAT_SP
        elif self._active_backend in ("mtk", "mtk_mac"):
            return CAT_MTK

        return CAT_GUI

    def record_log(self, line: str, category: str = "auto", dedupe: bool = False):
        """Record and persist a log entry to memory and disk.

        ``dedupe`` drops a byte-identical message recorded seconds ago. Use it
        for sources that echo the same physical event twice (a tool printing to
        stdout while also reporting through its callback).
        """
        msg = str(line or "").rstrip("\r\n")
        if not msg:
            return
        # A failure while persisting is itself logged; without this guard that
        # debug record would come back through the logging handler forever.
        if getattr(_LOCAL, "recording", False):
            return
        _LOCAL.recording = True
        try:
            self._record(msg, category, dedupe)
        finally:
            _LOCAL.recording = False

    def _record(self, msg: str, category: str, dedupe: bool):
        now = time.monotonic()
        ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        formatted = f"[{ts}] {msg}"

        cat = category if category != "auto" else self.classify_line(msg)
        if cat not in self._buffers:
            cat = CAT_GUI

        with _LOCK:
            if dedupe:
                last = self._recent_raw.get(msg)
                if last is not None and now - last < DEDUPE_WINDOW_SECONDS:
                    return
            self._recent_raw[msg] = now
            if len(self._recent_raw) > _MAX_RECENT_RAW:
                cutoff = now - DEDUPE_WINDOW_SECONDS
                self._recent_raw = {
                    k: v for k, v in self._recent_raw.items() if v >= cutoff
                }

            # 1. Update in-memory buffers
            for target_cat in (CAT_ALL, cat):
                buf = self._buffers[target_cat]
                buf.append(formatted)
                if len(buf) > self._max_buffer:
                    self._buffers[target_cat] = buf[-self._max_buffer:]

            # 2. Append to on-disk files
            try:
                for target_cat in (CAT_ALL, cat):
                    target_file = get_log_file(target_cat)
                    with open(target_file, "a", encoding="utf-8", errors="replace") as f:
                        f.write(formatted + "\n")
            except Exception as e:
                logger.debug("Failed appending log to %s: %s", cat, e)

    def start_flash_session(self, package_name: str, method: str, model: str = ""):
        """Log a prominent visual banner marking the start of a flash attempt."""
        self.set_active_backend(method)
        sep = "=" * 70
        ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        lines = [
            sep,
            f"=== INSTALL SESSION STARTED: {ts}",
            f"=== Software Package: {package_name}",
            f"=== Device Model:     {model or 'device'}",
            f"=== Flashing Method:  {method}",
            sep,
        ]
        target_cat = CAT_SP if method == "sp" else (CAT_MTK if method in ("mtk", "mtk_mac") else CAT_GUI)
        for ln in lines:
            self.record_log(ln, category=target_cat)

    def end_flash_session(self, success: bool, detail: str = ""):
        """Log a prominent visual banner marking the completion of a flash attempt."""
        target_cat = CAT_SP if self._active_backend == "sp" else (CAT_MTK if self._active_backend in ("mtk", "mtk_mac") else CAT_GUI)
        sep = "=" * 70
        ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        status_str = "SUCCESS" if success else f"FAILED ({detail or 'UNKNOWN'})"
        lines = [
            sep,
            f"=== INSTALL SESSION COMPLETED: {status_str} at {ts}",
            sep,
        ]
        for ln in lines:
            self.record_log(ln, category=target_cat)
        self.set_active_backend("")

    def get_lines(self, category: str = CAT_ALL) -> list[str]:
        """Retrieve all currently buffered lines for a category, reading from disk if buffer is empty."""
        with _LOCK:
            buf = self._buffers.get(category, [])
            if buf:
                return list(buf)

        # Fallback to reading file if buffer is currently empty
        fpath = get_log_file(category)
        if fpath.is_file():
            try:
                with open(fpath, "r", encoding="utf-8", errors="replace") as f:
                    return [ln.rstrip("\r\n") for ln in f.readlines()]
            except Exception:
                pass
        return []

    def get_display_lines(
        self, category: str = CAT_ALL, include_qt_log: bool = True
    ) -> list[str]:
        """Lines for a category, with SP Flash Tool's internal log appended.

        Returning lines rather than one blob lets the diagnostics view filter
        the result by date/time and by install session.
        """
        lines = self.get_lines(category)
        if category in (CAT_ALL, CAT_SP) and include_qt_log:
            qt_lines = _qt_log_section_lines()
            if qt_lines:
                lines = (lines + qt_lines) if lines else list(qt_lines)
        return lines

    def get_full_text(self, category: str = CAT_ALL, include_qt_log: bool = True) -> str:
        """Return the combined text of a category, optionally appending QT_FLASH_TOOL.log for SP."""
        return "\n".join(self.get_display_lines(category, include_qt_log))
